from .config import (
    BALL_DETECTOR_PATH,
    COURT_IMAGE_PATH,
    COURT_KEYPOINT_DETECTOR_PATH,
    OUTPUT_VIDEO_PATH,
    OUTPUT_VIDEOS_DIR,
    PLAYER_DETECTOR_PATH,
    SAMPLE_VIDEOS_DIR,
    STUBS_DEFAULT_PATH,
    TEMP_UPLOADS_DIR,
)
